// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 2.0.50727.1433
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------

namespace QFramework.TodoList
{
    using System;
    using System.Collections;
    using System.Collections.Generic;
    using System.Linq;
    using UnityEngine;
    using UnityEngine.UI;
    
    
    public partial class PanelTodoList
    {
        
        public const string NAME = "PanelTodoList";
        
        [SerializeField()]
        public UIListCtrl Container;
        
        [SerializeField()]
        public UITodoItem UITodoItem;
        
        [SerializeField()]
        public Button BtnCheckCompleted;
        
        [SerializeField()]
        public PanelAddItem PanelAddItem;
        
        [SerializeField()]
        public Image EventMask;
        
        private PanelTodoListData mPrivateData = null;
        
        public PanelTodoListData mData
        {
            get
            {
                return mPrivateData ?? (mPrivateData = new PanelTodoListData());
            }
            set
            {
                mUIData = value;
                mPrivateData = value;
            }
        }
        
        protected override void ClearUIComponents()
        {
            Container = null;
            UITodoItem = null;
            BtnCheckCompleted = null;
            PanelAddItem = null;
            EventMask = null;
            mData = null;
        }
    }
}
