// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 2.0.50727.1433
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------

namespace QFramework.TodoList
{
    using System;
    using System.Collections;
    using System.Collections.Generic;
    using System.Linq;
    using UnityEngine;
    using UnityEngine.UI;


    public class PanelCompletedListData : QFramework.UIPanelData
    {
        // ��������
        public TodoList Model = new TodoList()
        {
            mTodoItems = new List<TodoItem>()
            {
                new TodoItem() { Completed = true, Content = "need to study" },
                new TodoItem() { Completed = true, Content = "need to have lunch" },
            }
        };
    }

    public enum CompletedListEvent
    {
        Start = PanelTodoListEvent.End,
        End,
    }
    
    public partial class PanelCompletedList : QFramework.UIPanel
    {
        
        public void GenerateCompletedItem()
        {
            Container.DestroyAllChild();
            if (mData.Model.mTodoItems.IsNotNull())
            {
                mData.Model.mTodoItems.Where(item => item.Completed).ForEach(item =>
                {
                    UICompletedItem.Instantiate()
                                .Parent(Container)
                                .LocalIdentity()
                                .ApplySelfTo(self => self.Init(item))
                                .Show();
                });
            }
        }

        protected override void ProcessMsg(int eventId, QFramework.QMsg msg)
        {
        }

        protected override void RegisterUIEvent()
        {
            base.RegisterUIEvent();

            // �鿴todo List�¼�
            BtnCheckTodo.onClick.AddListener(() =>
            {
                CloseSelf();
                UIMgr.OpenPanel<PanelTodoList>(new PanelTodoListData()
                {
                    Model = mData.Model,
                });
            });
        }

        protected override void OnInit(QFramework.IUIData uiData)
        {
            mData = uiData as PanelCompletedListData ?? new PanelCompletedListData();
            // please add init code here

            GenerateCompletedItem();
        }
        
        protected override void OnOpen(QFramework.IUIData uiData)
        {
        }
        
        protected override void OnShow()
        {
        }
        
        protected override void OnHide()
        {
        }
        
        protected override void OnClose()
        {
        }
    }
}
